---
title: "COMPSCIX 415.2 Homework 1"
author: "Dai_Zhechen"
date: "2019/2/3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My Github repository for my assignments can be found at this URL:[https://github.com/zhechendai/compscix-415-2-assignments]

```{r load_packages, warning=FALSE, message=FALSE}
library(mdsr)
library(tidyverse)
data('WorldCities')
```

### Question 1:
There are 23,018 observations and 10 variables in this data set. The variables are code, name, latitude, longitude, country, countryRegion, population, regionCode, region, data.

```{r}
glimpse(WorldCities)
```
```{r}
WorldCities <- head(WorldCities, 200) # 200 rows, easiest way
```
```{r}
country_col <- WorldCities$country #pull a column, quickest way
unique(country_col)
```

### Question 2:
```{r}
region_col <- WorldCities$region #pull a column, quickest way
unique(region_col)
```

### Question 3:
```{r}
WorldCities %>% select(country) %>% unique()
```


```{r}
WorldCities %>% ggplot(aes(x = population)) + geom_histogram()
```

### Question 4:
```{r warning=FALSE, message=FALSE}
WorldCities %>% ggplot(aes(x = population)) + geom_histogram() +xlab('City Population')+ylab('Latest Count')+ggtitle('The Distribution of City Populations')+theme_bw()
```
